### ISSUE TITLE
Pagina popup-ului extensiei afișează un scrollbar

### ISSUE THREAD

**Issue by ezluci** [AlexHodo/SOLINFO.ro-Chrome-Extension#2]
Din cauza modificărilor recente la design-ul paginii, pagina de popup a extensiei nu mai este afișată cum trebuie. Trebuie setat atributul `height` din fișierul `manfiest.json` al extensiei sau din fișierul `/src/routes/Home.tsx` la o valoare mai mare pentru ca scrollbar-ul din dreapta să dispară iar pagina să fie afișată corespunzător.
![image](https://user-images.githubusercontent.com/68049793/133782120-d07a853b-fad7-4fbf-aacc-9edafd0c02f5.png)

**Comment by AlexHodo** [comment]
Extensiile Chrome pot avea o inaltime de maxim 600px. Momentan, inaltimea extensiei este de 550px. O sa o cresc la 600px, iar, daca problema persista, o sa modific structura paginii din iframe asa incat sa se incadreze in 600px.
Inaltimea body-ului e setata aici:
https://github.com/AlexHodo/SOLINFO.ro-Chrome-Extension/blob/547e8c0ef8316036e09f04bf2178f0f7bfa359e2/src/index.css#L3

**Comment by AlexHodo** [comment]
https://github.com/AlexHodo/SOLINFO.ro-Chrome-Extension/commit/b8bae1b6cff653ed7cb6a77d10a52c8a756d3a51 Am maximizat inaltimea extensiei. Ramane sa minimizez inaltimea paginii din iframe in proiectul https://github.com/AlexHodo/SOLINFO.ro-Client (fisierul https://github.com/AlexHodo/SOLINFO.ro-Client/blob/master/src/pages/SolutieNoua.js).
